import json
import uuid
import datetime
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Preformatted, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

from database import get_db
import report_builder

async def generate_report(incident_id: str, generated_by: str) -> dict:
    db = await get_db()
    
    # Check if a final report already exists to prevent duplication
    existing = await db.reports.find_one({"incident_id": incident_id, "status": "FINAL"}, {"_id": 0})
    if existing:
        return existing
        
    report_object = await report_builder.build_report_object(incident_id, generated_by)
    report_id = str(uuid.uuid4())
    
    report_doc = {
        "report_id": report_id,
        "incident_id": incident_id,
        "created_at": datetime.datetime.utcnow().isoformat(),
        "generated_by": generated_by,
        "generated_at": report_object["metadata"]["generated_date"],
        "report_version": "1.0",
        "schema_version": report_object["metadata"]["schema_version"],
        "ai_pipeline_version": report_object["metadata"]["ai_pipeline_version"],
        "system_version": report_object["metadata"]["system_version"],
        "status": "FINAL",
        "report_hash": report_object["metadata"]["report_hash"],
        "formats": ["pdf", "html", "markdown", "json"],
        "report_object": report_object
    }
    
    await db.reports.insert_one(report_doc)
    del report_doc["_id"]
    return report_doc

async def get_report(report_id: str) -> dict:
    db = await get_db()
    report = await db.reports.find_one({"report_id": report_id}, {"_id": 0})
    if not report:
        raise ValueError("Report not found.")
    return report

def export_json(report_object: dict) -> str:
    return json.dumps(report_object, indent=2)

def export_markdown(report_object: dict) -> str:
    md = f"# Enterprise Compliance Report\n\n"
    md += f"**Report ID**: {report_object['metadata'].get('report_hash', 'N/A')}\n"
    md += f"**Generated At**: {report_object['metadata']['generated_date']}\n"
    md += f"**Generated By**: {report_object['metadata']['generated_by']}\n\n"
    
    md += "## Incident Overview\n"
    for k, v in report_object['incident_overview'].items():
        md += f"- **{k.replace('_', ' ').title()}**: {v}\n"
        
    md += "\n## AI Executive Summary\n"
    md += f"- **Risk Trend**: {report_object['prediction_snapshot'].get('prediction', {}).get('trend', 'Unknown')}\n"
    md += f"- **Health Score**: {report_object['analytics_snapshot'].get('conversation_health_score', 'N/A')}/100\n"
    md += f"- **Copilot Brief**: {report_object['copilot_snapshot'].get('answer', 'N/A')}\n"
    
    return md

def export_html(report_object: dict) -> str:
    # A simple HTML representation of the markdown
    md = export_markdown(report_object)
    html = "<html><body style='font-family: sans-serif; max-width: 800px; margin: auto; padding: 20px;'>"
    for line in md.split('\n'):
        if line.startswith('# '): html += f"<h1>{line[2:]}</h1>"
        elif line.startswith('## '): html += f"<h2>{line[3:]}</h2>"
        elif line.startswith('- '): html += f"<li>{line[2:]}</li>"
        elif line.strip() == '': html += "<br/>"
        else: html += f"<p>{line}</p>"
    html += "</body></html>"
    return html

def export_pdf(report_object: dict) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    
    # Create custom styles
    title_style = styles['Heading1']
    subtitle_style = styles['Heading2']
    normal_style = styles['Normal']
    
    elements = []
    
    # 1. Cover Page / Header
    elements.append(Paragraph("Enterprise Compliance Report", title_style))
    elements.append(Spacer(1, 12))
    
    meta = report_object.get("metadata", {})
    elements.append(Paragraph(f"<b>Report Hash:</b> {meta.get('report_hash', 'N/A')}", normal_style))
    elements.append(Paragraph(f"<b>Generated At:</b> {meta.get('generated_date', 'N/A')}", normal_style))
    elements.append(Paragraph(f"<b>Generated By:</b> {meta.get('generated_by', 'N/A')}", normal_style))
    elements.append(Spacer(1, 24))
    
    # 2. Incident Overview
    elements.append(Paragraph("Incident Overview", subtitle_style))
    overview_data = [["Property", "Value"]]
    for k, v in report_object.get("incident_overview", {}).items():
        overview_data.append([k.replace("_", " ").title(), str(v)])
        
    t = Table(overview_data, colWidths=[200, 300])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.grey),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0,0), (-1,0), 12),
        ('BACKGROUND', (0,1), (-1,-1), colors.beige),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    elements.append(t)
    elements.append(Spacer(1, 24))
    
    # 3. AI Executive Summary
    elements.append(Paragraph("AI Executive Summary", subtitle_style))
    prediction = report_object.get("prediction_snapshot", {}).get("prediction", {})
    analytics = report_object.get("analytics_snapshot", {})
    copilot = report_object.get("copilot_snapshot", {})
    
    elements.append(Paragraph(f"<b>Risk Trend:</b> {prediction.get('trend', 'Unknown')}", normal_style))
    elements.append(Paragraph(f"<b>Conversation Health Score:</b> {analytics.get('conversation_health_score', 'N/A')}/100", normal_style))
    elements.append(Spacer(1, 12))
    elements.append(Paragraph("<b>Copilot Brief:</b>", normal_style))
    elements.append(Paragraph(copilot.get("answer", "N/A"), normal_style))
    
    # Build the PDF
    doc.build(elements)
    
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
