import json
import uuid
import datetime
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Preformatted, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

def export_pdf(report_object: dict) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    
    title_style = styles['Heading1']
    subtitle_style = styles['Heading2']
    normal_style = styles['Normal']
    
    elements = []
    
    elements.append(Paragraph("Enterprise Compliance Report", title_style))
    elements.append(Spacer(1, 12))
    
    meta = report_object.get("metadata", {})
    elements.append(Paragraph(f"<b>Report Hash:</b> {meta.get('report_hash', 'N/A')}", normal_style))
    elements.append(Paragraph(f"<b>Generated At:</b> {meta.get('generated_date', 'N/A')}", normal_style))
    elements.append(Paragraph(f"<b>Generated By:</b> {meta.get('generated_by', 'N/A')}", normal_style))
    elements.append(Spacer(1, 24))
    
    elements.append(Paragraph("Incident Overview", subtitle_style))
    overview_data = [["Property", "Value"]]
    for k, v in report_object.get("incident_overview", {}).items():
        overview_data.append([k.replace("_", " ").title(), str(v)])
        
    t = Table(overview_data, colWidths=[200, 300])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.grey),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0,0), (-1,0), 12),
        ('BACKGROUND', (0,1), (-1,-1), colors.beige),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    elements.append(t)
    elements.append(Spacer(1, 24))
    
    elements.append(Paragraph("AI Executive Summary", subtitle_style))
    prediction = report_object.get("prediction_snapshot", {}).get("prediction", {})
    analytics = report_object.get("analytics_snapshot", {})
    copilot = report_object.get("copilot_snapshot", {})
    
    elements.append(Paragraph(f"<b>Risk Trend:</b> {prediction.get('trend', 'Unknown')}", normal_style))
    elements.append(Paragraph(f"<b>Conversation Health Score:</b> {analytics.get('conversation_health_score', 'N/A')}/100", normal_style))
    elements.append(Spacer(1, 12))
    elements.append(Paragraph("<b>Copilot Brief:</b>", normal_style))
    elements.append(Paragraph(copilot.get("answer", "N/A"), normal_style))
    
    doc.build(elements)
    
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes

mock_report = {
    "metadata": {
        "generated_date": "2023-01-01",
        "generated_by": "admin",
        "report_hash": "12345"
    },
    "incident_overview": {
        "incident_id": "i-123"
    },
    "analytics_snapshot": {},
    "prediction_snapshot": {},
    "copilot_snapshot": {
        "answer": "This is a summary.\nIt has newlines."
    }
}

try:
    pdf_bytes = export_pdf(mock_report)
    print("PDF generated. Length:", len(pdf_bytes))
except Exception as e:
    import traceback
    traceback.print_exc()
