import React, { useState } from 'react';
import { FileText, Download, RefreshCw, Copy, Activity, ShieldAlert, Heart } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { API_URL } from '../../services/api';

export default function ConversationSummaryPanel({ conversationId, participants, isGroup }) {
  const { user } = useAuth();
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(false);
  const [summaryType, setSummaryType] = useState('moderator');
  const [error, setError] = useState('');

  const generateSummary = async () => {
    setLoading(true);
    setError('');
    try {
      const response = await fetch(`${API_URL}/api/conversation/summary`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${user.access_token}`
        },
        body: JSON.stringify({
          conversation_id: conversationId,
          summary_type: summaryType,
          participants: participants,
          is_group: isGroup
        })
      });

      if (!response.ok) throw new Error('Failed to generate summary');
      const data = await response.json();
      setSummary(data);
    } catch (err) {
      setError(err.message);
    }
    setLoading(false);
  };

  const copyToClipboard = () => {
    if (summary) {
      navigator.clipboard.writeText(summary.summary_text);
    }
  };

  const exportSummary = (format) => {
    if (!summary) return;
    
    let content = summary.summary_text;
    let mime = 'text/plain';
    let ext = '.txt';

    if (format === 'markdown') {
      content = `# Conversation Summary (${summaryType})\n\n**Health:** ${summary.conversation_health}\n**Risk Level:** ${summary.risk_level}\n\n## Summary\n${summary.summary_text}\n\n*Generated by ${summary.model_used} in ${summary.generation_time_ms}ms*`;
      mime = 'text/markdown';
      ext = '.md';
    } else if (format === 'pdf') {
      // Stub for PDF generation
      alert('PDF generation requires a library like html2pdf or jspdf. Exporting as text for now.');
    }

    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `summary-${conversationId}${ext}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-gray-900 border border-white/10 rounded-2xl p-6">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-bold text-white flex items-center gap-2">
          <FileText className="w-5 h-5 text-emerald-400" />
          AI Intelligence Engine
        </h2>
        
        <div className="flex gap-2">
          <select 
            className="bg-black/50 border border-white/10 rounded-lg text-sm text-gray-300 p-2"
            value={summaryType}
            onChange={(e) => setSummaryType(e.target.value)}
          >
            <option value="moderator">Moderator</option>
            <option value="user">User</option>
            <option value="incident">Incident</option>
            <option value="daily">Daily Overview</option>
            <option value="weekly">Weekly Overview</option>
          </select>
          <button 
            onClick={generateSummary}
            disabled={loading}
            className="btn-primary p-2 rounded-lg text-sm flex items-center gap-1"
          >
            <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
            {summary ? 'Regenerate' : 'Generate'}
          </button>
        </div>
      </div>

      {error && <div className="text-red-400 text-sm mb-4">{error}</div>}

      {summary && (
        <div className="space-y-4">
          <div className="grid grid-cols-3 gap-3">
            <div className="bg-black/20 p-3 rounded-xl border border-white/5">
              <div className="flex items-center gap-1 text-gray-400 text-xs mb-1"><Activity className="w-3 h-3"/> State</div>
              <div className="text-sm font-bold text-white">{summary.risk_level}</div>
            </div>
            <div className="bg-black/20 p-3 rounded-xl border border-white/5">
              <div className="flex items-center gap-1 text-gray-400 text-xs mb-1"><Heart className="w-3 h-3"/> Health</div>
              <div className="text-sm font-bold text-white">{summary.conversation_health}/100</div>
            </div>
            <div className="bg-black/20 p-3 rounded-xl border border-white/5">
              <div className="flex items-center gap-1 text-gray-400 text-xs mb-1"><ShieldAlert className="w-3 h-3"/> Emotion</div>
              <div className="text-sm font-bold text-white">{summary.dominant_emotion}</div>
            </div>
          </div>

          <div className="bg-black/40 p-4 rounded-xl border border-white/5 relative group">
            <p className="text-gray-300 text-sm leading-relaxed">{summary.summary_text}</p>
            
            <button onClick={copyToClipboard} className="absolute top-2 right-2 p-1.5 bg-gray-800 rounded-md text-gray-400 opacity-0 group-hover:opacity-100 transition-opacity">
              <Copy className="w-4 h-4" />
            </button>
          </div>

          <div className="flex justify-between items-center text-xs">
            <span className="text-gray-500">Model: {summary.model_used} | Latency: {summary.generation_time_ms}ms</span>
            <div className="flex gap-2">
              <button onClick={() => exportSummary('text')} className="text-gray-400 hover:text-white flex items-center gap-1">
                <Download className="w-3 h-3"/> TXT
              </button>
              <button onClick={() => exportSummary('markdown')} className="text-gray-400 hover:text-white flex items-center gap-1">
                <Download className="w-3 h-3"/> MD
              </button>
              <button onClick={() => exportSummary('pdf')} className="text-gray-400 hover:text-white flex items-center gap-1">
                <Download className="w-3 h-3"/> PDF
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
